Blockly.Blocks['lsh_120'] = {
  init: function() {
    this.appendValueInput("DIO0")
        .setCheck(null)
        .appendField("DIO0");
    this.appendValueInput("DIO1")
        .setCheck(null)
        .appendField("DIO1");
    this.appendValueInput("DIO2")
        .setCheck(null)
        .appendField("DIO2");
    this.appendValueInput("DIO3")
        .setCheck(null)
        .appendField("DIO3");
    this.appendValueInput("DIO4")
        .setCheck(null)
        .appendField("DIO4");
    this.appendValueInput("DIO5")
        .setCheck(null)
        .appendField("DIO5");
    this.appendValueInput("DIO6")
        .setCheck(null)
        .appendField("DIO6");
    this.appendValueInput("DIO7")
        .setCheck(null)
        .appendField("DIO7");
    this.appendValueInput("DIO8")
        .setCheck(null)
        .appendField("DIO8");
    this.appendValueInput("DIO9")
        .setCheck(null)
        .appendField("DIO9");
    this.appendValueInput("DIO10")
        .setCheck(null)
        .appendField("DIO10");
    this.appendValueInput("DIO11")
        .setCheck(null)
        .appendField("DIO11");
    this.appendValueInput("DIO12")
        .setCheck(null)
        .appendField("DIO12");
    this.appendValueInput("AIN1")
        .setCheck(null)
        .appendField("AIN1");
    this.appendValueInput("AIN2")
        .setCheck(null)
        .appendField("AIN2");
    this.appendValueInput("AIN3")
        .setCheck(null)
        .appendField("AIN3");
    this.appendValueInput("AIN4")
        .setCheck(null)
        .appendField("AIN4");
    this.appendValueInput("AIN5")
        .setCheck(null)
        .appendField("AIN5");
    this.appendValueInput("AIN6")
        .setCheck(null)
        .appendField("AIN6");
    this.appendValueInput("AIN7")
        .setCheck(null)
        .appendField("AIN7");
    this.appendValueInput("AIN8")
        .setCheck(null)
        .appendField("AIN8");
    this.setOutput(true, null);
    this.setColour(290);
    this.setTooltip('');
    this.setHelpUrl('http://openfpgaduino.github.io/');
  }
};
