Blockly.Blocks['lsh_100'] = {
  init: function() {
    this.appendValueInput("P0")
        .setCheck(null)
        .appendField("P0");
    this.appendValueInput("P1")
        .setCheck(null)
        .appendField("P1");
    this.appendValueInput("P2")
        .setCheck(null)
        .appendField("P2");
    this.appendValueInput("P3")
        .setCheck(null)
        .appendField("P3");
    this.appendValueInput("P4")
        .setCheck(null)
        .appendField("P4");
    this.appendValueInput("P5")
        .setCheck(null)
        .appendField("P5");
    this.appendValueInput("P6")
        .setCheck(null)
        .appendField("P6");
    this.appendValueInput("P7")
        .setCheck(null)
        .appendField("P7");
    this.appendValueInput("P8")
        .setCheck(null)
        .appendField("P8");
    this.appendValueInput("P9")
        .setCheck(null)
        .appendField("P9");
    this.appendValueInput("P10")
        .setCheck(null)
        .appendField("P10");
    this.appendValueInput("P11")
        .setCheck(null)
        .appendField("P11");
    this.appendValueInput("P12")
        .setCheck(null)
        .appendField("P12");
    this.appendValueInput("P13")
        .setCheck(null)
        .appendField("P13");
    this.appendValueInput("P14")
        .setCheck(null)
        .appendField("P14");
    this.appendValueInput("P15")
        .setCheck(null)
        .appendField("P15");
    this.appendValueInput("P16")
        .setCheck(null)
        .appendField("P16");
    this.appendValueInput("P17")
        .setCheck(null)
        .appendField("P17");
    this.appendValueInput("P18")
        .setCheck(null)
        .appendField("P18");
    this.appendValueInput("P19")
        .setCheck(null)
        .appendField("P19");
    this.appendValueInput("P20")
        .setCheck(null)
        .appendField("P20");
    this.appendValueInput("P21")
        .setCheck(null)
        .appendField("P21");
    this.appendValueInput("P22")
        .setCheck(null)
        .appendField("P22");
    this.appendValueInput("P23")
        .setCheck(null)
        .appendField("P23");
    this.appendValueInput("P24")
        .setCheck(null)
        .appendField("P24");
    this.appendValueInput("P25")
        .setCheck(null)
        .appendField("P25");
    this.setOutput(true, null);
    this.setColour(290);
    this.setTooltip('');
    this.setHelpUrl('http://openfpgaduino.github.io/');
  }
};
